  name: CI

  on: push

  jobs:
    build:
      name: Build and test
      environment: production
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Yarn Install
          uses: borales/actions-yarn@v3.0.0
          with:
            cmd: install

        - name: Yarn Build
          uses: borales/actions-yarn@v3.0.0
          with:
            cmd: build

        - name: Deploy
          uses: crazy-max/ghaction-github-pages@v1
          with:
            target_branch: deployed
            build_dir: build
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
