  name: CI

  on: push

  jobs:
    build:
      name: Build and test
      environment: production
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Yarn Install
          uses: borales/actions-yarn@v3.0.0
          with:
            cmd: install

        - name: Yarn Build
          uses: borales/actions-yarn@v3.0.0
          with:
            cmd: build
        
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Add build artifact
            title: Add build artifact
