  name: CI

  on: push

  jobs:
    build:
      name: Build and test
      environment: production
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@master

        - uses: borales/actions-yarn@v2.0.0
          with:
            node-version: 16
            cmd: install

        - uses: borales/actions-yarn@v2.0.0
          with:
            node-version: 16
            cmd: build
