  name: CI

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    build:
      name: Build and test
      environment: production
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Install Node.js
          uses: actions/setup-node@v2
            with:
              node-version: '16'

        - name: Cache Dependencies
          uses: actions/cache@v2
            with:
              path: '**/node_modules'
              key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    
        - name: Install Dependencies
          run: yarn install

        - name: Build
          run: yarn build

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          with:
            source-directory: 'build'
            destination-github-username: 'getroob'
            destination-repository-name: 'larissa-backend'
            target-directory: 'client'
