  name: CI

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    build:
      name: Build and test
      environment: production
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Yarn Install
          uses: borales/actions-yarn@v3.0.0
          with:
            cmd: install

        - name: Yarn Build
          uses: borales/actions-yarn@v3.0.0
          with:
            cmd: build

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          with:
            source-directory: 'build'
            destination-github-username: 'getroob'
            destination-repository-name: 'larissa-backend'
            target-directory: 'client/'
